server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_URL}:5432/${DB_NAME}?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jackson:
    mapper:
      accept-case-insensitive-enums: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
<<<<<<< HEAD
    org.hibernate.type.descriptor.sql: trace
=======
    org.hibernate.type.descriptor.sql: trace
>>>>>>> a7d1c1e1f0b1d3e4ce96d89b0a4223b212d1ffab
