#mysql? redis? ???? ?? ??
#spring:
#  datasource:
#    url: jdbc:mysql://${DB_URL}:3306/${DB_NAME}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database: mysql
#    hibernate:
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#  redis:
#    host: ${CACHE_URL}
#    port: 6379
#  main:
#    allow-bean-definition-overriding: true
#server:
#  port: 8080


server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_URL}:5432/${DB_NAME}?serverTimezone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jackson:
    mapper:
      accept-case-insensitive-enums: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
















